# Generated by Django 3.1.1 on 2021-04-24 02:42

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('price', models.IntegerField()),
                ('condition', models.CharField(choices=[('used', 'Used'), ('new', 'New')], max_length=10)),
                ('post_category', models.CharField(choices=[('sell', 'Sell'), ('buy', 'Buy')], max_length=10)),
                ('details', models.TextField(max_length=300)),
                ('location', models.CharField(max_length=50)),
                ('uploaded_time', models.DateTimeField(default=datetime.datetime(2021, 4, 24, 2, 42, 34, 261399))),
                ('phone', models.TextField(max_length=13)),
                ('url', models.TextField(max_length=40)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ManyToManyField(to='buysell.Category')),
            ],
            options={
                'ordering': ['uploaded_time'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buysell.product')),
            ],
        ),
    ]
