# Generated by Django 3.1.1 on 2021-04-24 02:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buysell', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='uploaded_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 24, 2, 42, 37, 37868)),
        ),
    ]
