# Generated by Django 3.1.1 on 2021-04-24 03:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buysell', '0002_auto_20210424_0242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='buysell.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='uploaded_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 24, 3, 4, 51, 662917)),
        ),
    ]
