# Generated by Django 3.1.1 on 2021-04-24 16:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buysell', '0004_auto_20210424_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_negotiable',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='uploaded_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 24, 16, 13, 19, 394622)),
        ),
    ]
