# Generated by Django 3.1.1 on 2021-04-24 16:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buysell', '0005_auto_20210424_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='uploaded_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 24, 16, 13, 21, 153260)),
        ),
    ]
