# Generated by Django 3.1.1 on 2021-04-24 22:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buysell', '0007_auto_20210424_2158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='image',
            name='products',
            field=models.ManyToManyField(to='buysell.Product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='uploaded_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 24, 22, 1, 10, 994708)),
        ),
    ]
