# Generated by Django 3.1.1 on 2021-04-24 22:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buysell', '0008_auto_20210424_2201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='products',
            new_name='product',
        ),
        migrations.AlterField(
            model_name='product',
            name='uploaded_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 24, 22, 12, 38, 939578)),
        ),
    ]
