# Generated by Django 3.1.1 on 2021-04-24 22:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buysell', '0009_auto_20210424_2212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ManyToManyField(blank=True, to='buysell.Image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='uploaded_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 24, 22, 34, 32, 527497)),
        ),
    ]
